kind: Namespace
apiVersion: v1
metadata:
  name: fs-svc
  labels:
    name: fs-svc
---
# Enables the pods in a deployment to be accessible from outside the cluster

apiVersion: v1
kind: Service
metadata:
  name: file-services-api-svc
  namespace: fs-svc
spec:
  selector:
    app: file-services-api
#  portForward:
#    - protocol: "TCP"
#      port: 8011
#      localPort: 9000
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
      name: file-services-api
#      nodePort: 30000
  type: LoadBalancer
#  type: NodePort
  loadBalancerIP: 172.16.7.242
---
# Deploy web api
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-services-api
  namespace: fs-svc
  labels:
    app: file-services-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: file-services-api
  template:
    metadata:
      labels:
        app: file-services-api
    spec:
      containers:
        - args:
            - gunicorn
            - -w
            - "4"
            - --worker-class
            - uvicorn.workers.UvicornWorker
            - api_app:app
            - --bind
            - 0.0.0.0:8080
          env:
            - name: file_server_api_url
              value: http://172.16.7.242/api
            - name: file_server_bind_ip
              value: 0.0.0.0
            - name: file_server_bind_port
              value: "8080"
            - name: file_server_db_auth_source
              value: lv-docs
            - name: file_server_db_host
              value: 192.168.18.36
            - name: file_server_db_password
              value: "123456"
            - name: file_server_db_port
              value: "27018"
            - name: file_server_db_replica_set
            - name: file_server_db_username
              value: admin-doc
            - name: file_server_es_url
              value: 'http://192.168.18.36:9200,'
            - name: file_server_root_url
              value: http://172.16.7.242
            - name: file_server_use_os_config
              value: '''true'''
          image: nttlong/lv-file:b9
          name: file-services-api
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources: { }
          volumeMounts:
          - name: tmp-upload
            mountPath: /app/tmp
          - name: fs-docs
            mountPath: /app/fs-docs
          - name: api-logs
            mountPath: /app/logs


      volumes:
       - name: tmp-upload
         hostPath: # hostPath volume
           path: /file-api # folder of worker node
       - name: fs-docs
         hostPath: # hostPath volume
           path: /fs-docs # folder of worker node
       - name: api-logs
         hostPath:
           path: /api_logs
       - name: fs-logs
         hostPath:
           path: /fs-logs
       - name: bk-logs
         hostPath:
           path: /fs_process_logs


---
# image thumb process
apiVersion: batch/v1
kind: Job
metadata:
  name: file-services-thumb-image
  namespace: fs-svc
spec:
  template:
    spec:
      containers:
      # Process thumb image container
        - args:
            - python3
            - /app/bk_services/thumb_image.py

          image: nttlong/lv-file:b9
          name: file-services-thumb-image
          imagePullPolicy: Always

          resources: { }
          volumeMounts:
            - name: tmp-upload
              mountPath: /app/tmp
            - name: fs-docs
              mountPath: /app/fs-docs
            - name: bk-logs
              mountPath: /app/logs
      volumes:
        - name: tmp-upload
          hostPath: # hostPath volume
            path: /file-api # folder of worker node
        - name: fs-docs
          hostPath: # hostPath volume
            path: /fs-docs # folder of worker node
        - name: api-logs
          hostPath:
            path: /api_logs
        - name: fs-logs
          hostPath:
            path: /fs-logs
        - name: bk-logs
          hostPath:
            path: /lv_file_bk_services
      restartPolicy: Never
  backoffLimit: 4
---
# video thumb process
apiVersion: batch/v1
kind: Job
metadata:
  name: file-services-thumb-video
  namespace: fs-svc
spec:
  template:
    spec:
      containers:

        - args:
            - python3
            - /app/bk_services/thumb_video.py

          image: nttlong/lv-file:b9
          name: file-services-thumb-video
          imagePullPolicy: Always

          resources: { }
          volumeMounts:
            - name: tmp-upload
              mountPath: /app/tmp
            - name: fs-docs
              mountPath: /app/fs-docs
            - name: bk-logs
              mountPath: /app/logs
      volumes:
        - name: tmp-upload
          hostPath: # hostPath volume
            path: /file-api # folder of worker node
        - name: fs-docs
          hostPath: # hostPath volume
            path: /fs-docs # folder of worker node
        - name: api-logs
          hostPath:
            path: /api_logs
        - name: fs-logs
          hostPath:
            path: /fs-logs
        - name: bk-logs
          hostPath:
            path: /lv_file_bk_services
      restartPolicy: Never
  backoffLimit: 4
---
# office thumb process
apiVersion: batch/v1
kind: Job
metadata:
  name: file-services-thumb-office
  namespace: fs-svc
spec:
  template:
    spec:
      containers:

        - args:
            - python3
            - /app/bk_services/thumb_office.py

          image: nttlong/lv-file:b9
          name: file-services-thumb-office
          imagePullPolicy: Always

          resources: { }
          volumeMounts:
            - name: tmp-upload
              mountPath: /app/tmp
            - name: fs-docs
              mountPath: /app/fs-docs
            - name: bk-logs
              mountPath: /app/logs
      volumes:
        - name: tmp-upload
          hostPath: # hostPath volume
            path: /file-api # folder of worker node
        - name: fs-docs
          hostPath: # hostPath volume
            path: /fs-docs # folder of worker node
        - name: api-logs
          hostPath:
            path: /api_logs
        - name: fs-logs
          hostPath:
            path: /fs-logs
        - name: bk-logs
          hostPath:
            path: /lv_file_bk_services
      restartPolicy: Never
  backoffLimit: 4
---
# pdf thumb process
apiVersion: batch/v1
kind: Job
metadata:
  name: file-services-thumb-pdf
  namespace: fs-svc
spec:
  template:
    spec:
      containers:

        - args:
            - python3
            - /app/bk_services/thumb_pdf.py

          image: nttlong/lv-file:b9
          name: file-services-thumb-pdf
          imagePullPolicy: Always

          resources: { }
          volumeMounts:
            - name: tmp-upload
              mountPath: /app/tmp
            - name: fs-docs
              mountPath: /app/fs-docs
            - name: bk-logs
              mountPath: /app/logs
      volumes:
        - name: tmp-upload
          hostPath: # hostPath volume
            path: /file-api # folder of worker node
        - name: fs-docs
          hostPath: # hostPath volume
            path: /fs-docs # folder of worker node
        - name: api-logs
          hostPath:
            path: /api_logs
        - name: fs-logs
          hostPath:
            path: /fs-logs
        - name: bk-logs
          hostPath:
            path: /lv_file_bk_services
      restartPolicy: Never
  backoffLimit: 4
---
# ocr pdf
apiVersion: batch/v1
kind: Job
metadata:
  name: file-services-ocr-pdf
  namespace: fs-svc
spec:
  template:
    spec:
      containers:

        - args:
            - python3
            - /app/bk_services/ocr_pdf.py

          image: nttlong/lv-file:b9
          name: file-services-ocr-pdf
          imagePullPolicy: Always

          resources: { }
          volumeMounts:
            - name: tmp-upload
              mountPath: /app/tmp
            - name: fs-docs
              mountPath: /app/fs-docs
            - name: bk-logs
              mountPath: /app/logs
      volumes:
        - name: tmp-upload
          hostPath: # hostPath volume
            path: /file-api # folder of worker node
        - name: fs-docs
          hostPath: # hostPath volume
            path: /fs-docs # folder of worker node
        - name: api-logs
          hostPath:
            path: /api_logs
        - name: fs-logs
          hostPath:
            path: /fs-logs
        - name: bk-logs
          hostPath:
            path: /lv_file_bk_services
      restartPolicy: Never
  backoffLimit: 4
---
#ocr image
apiVersion: batch/v1
kind: Job
metadata:
  name: file-services-ocr-image
  namespace: fs-svc
spec:
  template:
    spec:
      containers:

        - args:
            - python3
            - /app/bk_services/ocr_image.py

          image: nttlong/lv-file:b9
          name: file-services-ocr-image
          imagePullPolicy: Always

          resources: { }
          volumeMounts:
            - name: tmp-upload
              mountPath: /app/tmp
            - name: fs-docs
              mountPath: /app/fs-docs
            - name: bk-logs
              mountPath: /app/logs
      volumes:
        - name: tmp-upload
          hostPath: # hostPath volume
            path: /file-api # folder of worker node
        - name: fs-docs
          hostPath: # hostPath volume
            path: /fs-docs # folder of worker node
        - name: api-logs
          hostPath:
            path: /api_logs
        - name: fs-logs
          hostPath:
            path: /fs-logs
        - name: bk-logs
          hostPath:
            path: /lv_file_bk_services
      restartPolicy: Never
  backoffLimit: 4
---
# Process Elastic Search Index
apiVersion: batch/v1
kind: Job
metadata:
  name: file-services-es-index
  namespace: fs-svc
spec:
  template:
    spec:
      containers:

        - args:
            - bash
            - -c
            - 'python3 /app/bk_services/fs_es_index.py no-process'
          image: nttlong/lv-file:b9
          name: file-services-es-index
          imagePullPolicy: Always

          resources: { }
          volumeMounts:
            - name: tmp-upload
              mountPath: /app/tmp
            - name: fs-docs
              mountPath: /app/fs-docs
            - name: bk-logs
              mountPath: /app/logs
      volumes:
        - name: tmp-upload
          hostPath: # hostPath volume
            path: /file-api # folder of worker node
        - name: fs-docs
          hostPath: # hostPath volume
            path: /fs-docs # folder of worker node
        - name: api-logs
          hostPath:
            path: /api_logs
        - name: fs-logs
          hostPath:
            path: /fs-logs
        - name: bk-logs
          hostPath:
            path: /lv_file_bk_services
      restartPolicy: Never
  backoffLimit: 4
---
#fs crawler
apiVersion: batch/v1
kind: Job
metadata:
  name: file-services-fscrawler
  namespace: fs-svc
spec:
  template:
    spec:
      containers:

        - args:
            - bash
            - -c
            - ' sed -i "s/{FS_CRAWLER_INDEX}/lv-files-server-v2/g"  /app/py_fs_crawler/fs_config/_settings.yaml && sed  -i "s/{ES_URL}/http\:\/\/192.168.18.36:9200/g" /app/py_fs_crawler/fs_config/_settings.yaml && /usr/share/fscrawler/bin/fscrawler /app/py_fs_crawler/fs_config'

          image: nttlong/fscrawler:v2
          name: file-services-efscrawler
          imagePullPolicy: Always

          resources: { }
          volumeMounts:
            - name: tmp-upload
              mountPath: /app/tmp
            - name: fs-docs
              mountPath: /app/fs-docs
            - name: bk-logs
              mountPath: /app/logs
            - name: fs-logs
              mountPath: /usr/share/fscrawler/logs
      volumes:
        - name: tmp-upload
          hostPath: # hostPath volume
            path: /file-api # folder of worker node
        - name: fs-docs
          hostPath: # hostPath volume
            path: /fs-docs # folder of worker node
        - name: api-logs
          hostPath:
            path: /api_logs
        - name: fs-logs
          hostPath:
            path: /fs-logs
        - name: bk-logs
          hostPath:
            path: /lv_file_bk_services
      restartPolicy: Never
  backoffLimit: 4
---
# Cleansing chapel
apiVersion: batch/v1
kind: Job
metadata:
  name: file-services-cleansing-chapel
  namespace: fs-svc
spec:
  template:
    spec:
      containers:

        - args:
            - python3
            - /app/bk_services/cleansing_chapel.py

          image: nttlong/lv-file:b9
          name: file-services-cleansing-chapel
          imagePullPolicy: Always

          resources: { }
          volumeMounts:
            - name: tmp-upload
              mountPath: /app/tmp
            - name: fs-docs
              mountPath: /app/fs-docs
            - name: bk-logs
              mountPath: /app/logs
      volumes:
        - name: tmp-upload
          hostPath: # hostPath volume
            path: /file-api # folder of worker node
        - name: fs-docs
          hostPath: # hostPath volume
            path: /fs-docs # folder of worker node
        - name: api-logs
          hostPath:
            path: /api_logs
        - name: fs-logs
          hostPath:
            path: /fs-logs
        - name: bk-logs
          hostPath:
            path: /lv_file_bk_services
      restartPolicy: Never
  backoffLimit: 4
---
# Cleansing town

apiVersion: batch/v1
kind: Job
metadata:
  name: file-services-cleansing-town
  namespace: fs-svc
spec:
  template:
    spec:
      containers:

        - args:
            - python3
            - /app/bk_services/cleansing_town.py

          image: nttlong/lv-file:b9
          name: file-services-cleansing-town
          imagePullPolicy: Always

          resources: { }
          volumeMounts:
            - name: tmp-upload
              mountPath: /app/tmp
            - name: fs-docs
              mountPath: /app/fs-docs
            - name: bk-logs
              mountPath: /app/logs
      volumes:
        - name: tmp-upload
          hostPath: # hostPath volume
            path: /file-api # folder of worker node
        - name: fs-docs
          hostPath: # hostPath volume
            path: /fs-docs # folder of worker node
        - name: api-logs
          hostPath:
            path: /api_logs
        - name: fs-logs
          hostPath:
            path: /fs-logs
        - name: bk-logs
          hostPath:
            path: /lv_file_bk_services
      restartPolicy: Never
  backoffLimit: 4