kind: Namespace
apiVersion: v1
metadata:
  name: fs-c
  labels:
    name: fs-c
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fs-crawler
  namespace: fs-c
  labels:
    app: fs-crawler
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fs-crawler
  template:
    metadata:
      labels:
        app: fs-crawler
    spec:
      containers:
        - args:
            - bash
            - -c
            - ' sed -i "s/{FS_CRAWLER_INDEX}/lv-files-server-v2/g"  /app/py_fs_crawler/fs_config/_settings.yaml && sed  -i "s/{ES_URL}/http\:\/\/192.168.18.26:9200/g" /app/py_fs_crawler/fs_config/_settings.yaml && /usr/share/fscrawler/bin/fscrawler /app/py_fs_crawler/fs_config'

          image: nttlong/fscrawler
          name: file-services-fs-crawler
          imagePullPolicy: Always

          resources: { }
          volumeMounts:
            - name: tmp-upload
              mountPath: /app/tmp
            - name: fs-docs
              mountPath: /app/fs-docs
      volumes:
       - name: tmp-upload
         hostPath: # hostPath volume
           path: /file-api # folder of woker node
       - name: fs-docs
         hostPath: # hostPath volume
           path: /fs-docs # folder of woker node