kind: Namespace
apiVersion: v1
metadata:
  name: fs-job-thumb
  labels:
    name: fs-job-thumb
---

# kf-api Deployment
# Defines the deployment of the app running in a pod on any worker node
apiVersion: batch/v1
kind: Job
metadata:
  name: file-services-thumb-pdf
  namespace: fs-job-thumb

spec:

  template:
    spec:

      containers:
        # process thumb video container
        - args:
            - python3
            - /app/bk_services/thumb_pdf.py

          image: nttlong/lv-file:v3
          name: file-services-thumb-pdf
          imagePullPolicy: Always

          resources: { }
          volumeMounts:
            - name: tmp-upload
              mountPath: /app/tmp
            - name: fs-docs
              mountPath: /app/fs-docs
      volumes:
        - name: tmp-upload
          hostPath: # hostPath volume
            path: /file-api # folder of worker node
        - name: fs-docs
          hostPath: # hostPath volume
            path: /fs-docs # folder of worker node
        - name: api-logs
          hostPath:
            path: /api_logs
        - name: fs-logs
          hostPath:
            path: /fs-logs
      restartPolicy: Never
  backoffLimit: 4