apiVersion: v1
kind: Namespace
metadata:
  name: kafka-sn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: broker
  name: broker
  namespace: kafka-sn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: broker
    spec:
      containers:
        - name: broker
          image: docker.io/bitnami/kafka:3.3
          ports:
            - containerPort: 9092
            - containerPort: 29092
            - containerPort: 9999
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: $(MY_POD_IP):2181
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://$(MY_POD_IP):9092

        - name: zookeeper
          image: docker.io/bitnami/zookeeper:3.8
          ports:
            - containerPort: 2181
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
---
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: broker
  name: broker
  namespace: kafka-sn
spec:
  type: NodePort
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
      nodePort: 30992
