apiVersion: v1
kind: Namespace
metadata:
  name: kafka-sn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kafka-zookeeper
  name: kafka-zookeeper
  namespace: kafka-sn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-zookeeper
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kafka-zookeeper
    spec:
      containers:
        - env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"

          image: docker.io/bitnami/zookeeper:3.8
          name: kafka-zoo-keeper
          ports:
            - containerPort: 2181
          resources: {}
      hostname: kafka-zookeeper
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kafka-zookeeper
  name: kafka-zookeeper
  namespace: kafka-sn
spec:
  type: ClusterIP
  ports:
    - name: "2181"
      port: 2181
      targetPort: 2181
  selector:
    app: kafka-zookeeper
status:
  loadBalancer: {}
