#Full file service including:
# 1- Web API and Web app for documentation of storage
# 2- Video Process Thumb
version: '3.7'

services:
  build-mage:
    image: lv-file
    build:
      context: ./..
      dockerfile: ./composer/files-dockerfile
  web:
    image: lv-file
    container_name: lv-file-web
    hostname: web
    volumes:

      - ${PATH_LOCAL_DIR_IN_HOST}/web-api/logs/:/app/logs
      - ${PATH_LOCAL_DIR_IN_HOST}/web-api/tmp-upload/:/app/tmp
    command: python3 /app/api_app_dev_run.py --port 8000 --api-url http://${HOST_IP}:${API_PORT}
    restart: always
    ports:
      - ${API_PORT}:8000
  thumb-video:
    image: lv-file
    container_name: thumb-video
    volumes:
      - ${PATH_LOCAL_DIR_IN_HOST}/web-api/tmp-upload/:/app/tmp
      - ${PATH_LOCAL_DIR_IN_HOST}/web-api/logs/:/app/logs
      - ${PATH_LOCAL_DIR_IN_HOST}/fs/share-docs:/app/fs-docs
    command: python3 /app/bk_services/thumb_video.py
  thumb-image:
    image: lv-file
    container_name: thumb-image
    volumes:
      - ${PATH_LOCAL_DIR_IN_HOST}/web-api/tmp-upload/:/app/tmp
      - ${PATH_LOCAL_DIR_IN_HOST}/fs/share-docs:/app/fs-docs
    command: python3 /app/bk_services/thumb_image.py
  thumb-office:
    image: lv-file
    container_name: thumb-office
    volumes:
      - ${PATH_LOCAL_DIR_IN_HOST}/web-api/tmp-upload/:/app/tmp
      - ${PATH_LOCAL_DIR_IN_HOST}/fs/share-docs:/app/fs-docs
    command: python3 /app/bk_services/thumb_office.py
  thumb-pdf:
    image: lv-file
    container_name: thumb-pdf
    volumes:
      - ${PATH_LOCAL_DIR_IN_HOST}/web-api/tmp-upload/:/app/tmp
      - ${PATH_LOCAL_DIR_IN_HOST}/fs/share-docs:/app/fs-docs

    command: python3 /app/bk_services/thumb_pdf.py
  fs-crawler:
    image: fs-crawler
    container_name: fs-crawler
    build:
      context: ./..
      dockerfile: ./composer/fs-dockerfile
    command: >
      bash -c '
      sed -i "s/{FS_CRAWLER_INDEX}/${FS_CRAWLER_INDEX}/g"  /app/py_fs_crawler/fs_config/_settings.yaml &&
      sed  -i "s/{ES_URL}/http\:\/\/${ES_URL}/g" /app/py_fs_crawler/fs_config/_settings.yaml &&
      /usr/share/fscrawler/bin/fscrawler /app/py_fs_crawler/fs_config'
    volumes:
      - ${PATH_LOCAL_DIR_IN_HOST}/web-api/tmp-upload/:/app/tmp
      - ${PATH_LOCAL_DIR_IN_HOST}/fs/share-docs:/app/fs-docs
      - ${PATH_LOCAL_DIR_IN_HOST}/fs/fs-logs:/usr/share/fscrawler/logs

  files-es-index-all-office-files:
    image: lv-file
    container_name: files-es-index-all-office-files
    volumes:
      - ${PATH_LOCAL_DIR_IN_HOST}/web-api/tmp-upload/:/app/tmp
      - ${PATH_LOCAL_DIR_IN_HOST}/fs/share-docs:/app/fs-docs
    command: python3 /app/bk_services/fs_es_index.py
#
  ocr-image:
    image: lv-file
    volumes:
      - ${PATH_LOCAL_DIR_IN_HOST}/web-api/tmp-upload/:/app/tmp
      - ${PATH_LOCAL_DIR_IN_HOST}/fs/share-docs:/app/fs-docs

    command: python3 /app/bk_services/ocr_image.py
    container_name: ocr-image
  ocr-pdf:
    image: lv-file
    volumes:
      - ${PATH_LOCAL_DIR_IN_HOST}/web-api/tmp-upload/:/app/tmp
      - ${PATH_LOCAL_DIR_IN_HOST}/fs/share-docs:/app/fs-docs

    command: python3 /app/bk_services/ocr_pdf.py
    container_name: ocr-pdf
