#Full file service including:
# 1- Web API and Web app for documentation of storage
# 2- VideoService Process Thumb
version: '3.7'

services:
#  build-mage:
#    image: lv-file
#    build:
#      context: ./..
#      dockerfile: ./composer/files-dockerfile
  web:
    image: nttlong/lv-file:rc.0.1.5
    container_name: xdoc
    hostname: xdoc
    volumes:

      - ${PATH_LOCAL_DIR_IN_HOST}/web-api/logs/:/app/logs
      - ${PATH_LOCAL_DIR_IN_HOST}/web-api/tmp-upload/:/app/tmp
#    command: python3 /app/test_cy_docs.py
    command: python3 /app/cy_xdoc/server.py host_url=http://172.16.13.72:8014/v-02 bind=0.0.0.0:80 db.host=192.168.18.36 db.port=27018 db.username=admin-doc db.password=123456 db.authSource=lv-docs admin_db_name=lv-docs elastic_search.server=http://192.168.18.36:9200 elastic_search.prefix_index=lv-codx  w:4 interface=asgi3 timeout_keep_alive=3600
#    command: ls /app/enig_frames/services/ext_libs
#    command: python3 /app/test_tika.py
#    command: ls /app
#    command: python3 /app/hypercorn_start.py binding_port=80 db.host=172.16.7.25 db.port=27018 db.username= db.password= db.authSource= db.authMechanism= admin_db_name=enigma-media
# Run QC Test Codx
#    command: python3 /app/hypercorn_start.py binding_port=80 db.host=192.168.18.36 db.port=27018 db.username=admin-doc db.password=123456 db.authSource=lv-docs admin_db_name=lv-docs elastic_search.server=http://192.168.18.36:9200 elastic_search.prefix_index=lv-codx
#    command: python3 /app/uvicorn_start.py binding_port=80 db.host=192.168.18.36 db.port=27018 db.username=admin-doc db.password=123456 db.authSource=lv-docs admin_db_name=lv-docs elastic_search.server=http://192.168.18.36:9200 elastic_search.prefix_index=lv-codx w:10
#    command: hypercorn api_app:app -w 4 --bind '0.0.0.0:80'
#    command: python3 /app/api_app_dev_run.py --port 8000 --api-url http://${HOST_IP}:${API_PORT}
#    command: gunicorn -w 4 --worker-class uvicorn.workers.UvicornWorker api_app:app --bind 0.0.0.0:80


    ports:
      - ${API_PORT}:80

#      - jinja_templates_dir=./app/templates
#  thumb-video:
#    image: lv-file
#    container_name: thumb-video
#    volumes:
#      - ${PATH_LOCAL_DIR_IN_HOST}/kb-logs/:/app/logs
#      - ${PATH_LOCAL_DIR_IN_HOST}/web-api/tmp-upload/:/app/tmp
#      - ${PATH_LOCAL_DIR_IN_HOST}/web-api/logs/:/app/logs
#      - ${PATH_LOCAL_DIR_IN_HOST}/fs/share-docs:/app/fs-docs
#    command: python3 /app/bk_services/thumb_video.py tmp-upload-folder=/app/tmp msg-folder=${MSG_FOLDER} fs-path=${FS_PATH} share-key=${SHARE_KEY} db-configuration=${DB_CONFIG}
#  thumb-image:
#    image: lv-file
#    container_name: thumb-image
#    volumes:
#      - ${PATH_LOCAL_DIR_IN_HOST}/kb-logs/:/app/logs
#      - ${PATH_LOCAL_DIR_IN_HOST}/web-api/tmp-upload/:/app/tmp
#      - ${PATH_LOCAL_DIR_IN_HOST}/fs/share-docs:/app/fs-docs
#    command: python3 /app/bk_services/thumb_image.py tmp-upload-folder=/app/tmp msg-folder=${MSG_FOLDER} fs-path=${FS_PATH} share-key=${SHARE_KEY} db-configuration=${DB_CONFIG}
#  thumb-office:
#    image: lv-file
#    container_name: thumb-office
#    volumes:
#      - ${PATH_LOCAL_DIR_IN_HOST}/kb-logs/:/app/logs
#      - ${PATH_LOCAL_DIR_IN_HOST}/web-api/tmp-upload/:/app/tmp
#      - ${PATH_LOCAL_DIR_IN_HOST}/fs/share-docs:/app/fs-docs
#    command: python3 /app/bk_services/thumb_office.py tmp-upload-folder=/app/tmp msg-folder=${MSG_FOLDER} fs-path=${FS_PATH} share-key=${SHARE_KEY} db-configuration=${DB_CONFIG}
#  thumb-pdf:
#    image: lv-file
#    container_name: thumb-pdf
#    volumes:
#      - ${PATH_LOCAL_DIR_IN_HOST}/kb-logs/:/app/logs
#      - ${PATH_LOCAL_DIR_IN_HOST}/web-api/tmp-upload/:/app/tmp
#      - ${PATH_LOCAL_DIR_IN_HOST}/fs/share-docs:/app/fs-docs
#
#    command: python3 /app/bk_services/thumb_pdf.py tmp-upload-folder=/app/tmp msg-folder=${MSG_FOLDER} fs-path=${FS_PATH} share-key=${SHARE_KEY} db-configuration=${DB_CONFIG}
#  fs-crawler:
#    image: nttlong/fscrawler:v2
#    container_name: fs-crawler
##    build:
##      context: ./..
##      dockerfile: ./composer/fs-dockerfile
#    command: >
#      bash -c '
#
#      sed -i "s/{FS_CRAWLER_INDEX}/${FS_CRAWLER_INDEX}/g"  /app/py_fs_crawler/fs_config/_settings.yaml &&
#      sed  -i "s/{ES_URL}/http\:\/\/${ES_URL}/g" /app/py_fs_crawler/fs_config/_settings.yaml &&
#      /usr/share/fscrawler/bin/fscrawler /app/py_fs_crawler/fs_config'
#    volumes:
#      - ${PATH_LOCAL_DIR_IN_HOST}/web-api/tmp-upload/:/app/tmp
#      - ${PATH_LOCAL_DIR_IN_HOST}/fs/share-docs:/app/fs-docs
#      - ${PATH_LOCAL_DIR_IN_HOST}/fs/fs-logs:/usr/share/fscrawler/logs
#
#  files-es-index-all-office-files:
#    image: lv-file
#    container_name: files-es-index-all-office-files
#    volumes:
#      - ${PATH_LOCAL_DIR_IN_HOST}/kb-logs/:/app/logs
#      - ${PATH_LOCAL_DIR_IN_HOST}/web-api/tmp-upload/:/app/tmp
#      - ${PATH_LOCAL_DIR_IN_HOST}/fs/share-docs:/app/fs-docs
#    command: python3 /app/bk_services/fs_es_index.py tmp-upload-folder=/app/tmp msg-folder=${MSG_FOLDER} fs-path=${FS_PATH} share-key=${SHARE_KEY} db-configuration=${DB_CONFIG}
##
#  ocr-image:
#    image: lv-file
#    volumes:
#      - ${PATH_LOCAL_DIR_IN_HOST}/kb-logs/:/app/logs
#      - ${PATH_LOCAL_DIR_IN_HOST}/web-api/tmp-upload/:/app/tmp
#      - ${PATH_LOCAL_DIR_IN_HOST}/fs/share-docs:/app/fs-docs
#
#    command: python3 /app/bk_services/ocr_image.py tmp-upload-folder=/app/tmp msg-folder=${MSG_FOLDER} fs-path=${FS_PATH} share-key=${SHARE_KEY} db-configuration=${DB_CONFIG}
#    container_name: ocr-image
#  ocr-pdf:
#    image: lv-file
#    volumes:
#      - ${PATH_LOCAL_DIR_IN_HOST}/kb-logs/:/app/logs
#      - ${PATH_LOCAL_DIR_IN_HOST}/web-api/tmp-upload/:/app/tmp
#      - ${PATH_LOCAL_DIR_IN_HOST}/fs/share-docs:/app/fs-docs
#
#    command: python3 /app/bk_services/ocr_pdf.py tmp-upload-folder=/app/tmp msg-folder=${MSG_FOLDER} fs-path=${FS_PATH} share-key=${SHARE_KEY} db-configuration=${DB_CONFIG}
#    container_name: ocr-pdf
#  cleansing-chapel:
#    image: lv-file
#    volumes:
#      - ${PATH_LOCAL_DIR_IN_HOST}/kb-logs/:/app/logs
#      - ${PATH_LOCAL_DIR_IN_HOST}/web-api/tmp-upload/:/app/tmp
#      - ${PATH_LOCAL_DIR_IN_HOST}/fs/share-docs:/app/fs-docs
#
#    command: python3 /app/bk_services/cleansing_chapel.py tmp-upload-folder=/app/tmp msg-folder=${MSG_FOLDER} fs-path=${FS_PATH} share-key=${SHARE_KEY} db-configuration=${DB_CONFIG}
#    container_name: cleansing-chapel
#  cleansing-town:
#    image: lv-file
#    volumes:
#      - ${PATH_LOCAL_DIR_IN_HOST}/kb-logs/:/app/logs
#      - ${PATH_LOCAL_DIR_IN_HOST}/web-api/tmp-upload/:/app/tmp
#      - ${PATH_LOCAL_DIR_IN_HOST}/fs/share-docs:/app/fs-docs
#
#    command: python3 /app/bk_services/cleansing_town.py tmp-upload-folder=/app/tmp msg-folder=${MSG_FOLDER} fs-path=${FS_PATH} share-key=${SHARE_KEY} db-configuration=${DB_CONFIG}
#    container_name: cleansing-town
