#Full file service including:
# 1- Web API and Web app for documentation of storage
# 2- Video Process Thumb
version: '3.7'

services:
  #build-mage:
  #  image: lv-file
  #  build:
  #    context: ./..
  #    dockerfile: ./composer/files-dockerfile
  web:
    image: nttlong/lv-file:b19
    container_name: lv-file-web
    hostname: web
    volumes:

      - ${PATH_LOCAL_DIR_IN_HOST}/web-api/logs/:/app/logs
      - ${PATH_LOCAL_DIR_IN_HOST}/web-api/tmp-upload/:/app/tmp
#    command: python3 /app/api_app_dev_run.py --port 8000 --api-url http://${HOST_IP}:${API_PORT}
    command: gunicorn -w 4 --worker-class uvicorn.workers.UvicornWorker api_app:app --bind 0.0.0.0:80


    ports:
      - ${API_PORT}:80
    environment:
      - file_server_use_os_config='true'
      - file_server_db_host=192.168.18.36
      - file_server_db_port=27018
      - file_server_db_auth_source=lv-docs
      - file_server_db_replica_set=
      - file_server_db_username=admin-doc
      - file_server_db_password=123456
      - file_server_bind_port=80
      - file_server_bind_ip=0.0.0.0
      - file_server_root_url=http://${HOST_IP}:${API_PORT}
      - file_server_api_url=http://${HOST_IP}:${API_PORT}/api
      - file_server_es_url=http://${ES_URL},
  thumb-video:
    image: nttlong/lv-file:b19
    container_name: thumb-video
    volumes:
      - ${PATH_LOCAL_DIR_IN_HOST}/web-api/tmp-upload/:/app/tmp
      - ${PATH_LOCAL_DIR_IN_HOST}/web-api/logs/:/app/logs
      - ${PATH_LOCAL_DIR_IN_HOST}/fs/share-docs:/app/fs-docs
    command: python3 /app/bk_services/thumb_video.py
  thumb-image:
    image: nttlong/lv-file:b19
    container_name: thumb-image
    volumes:
      - ${PATH_LOCAL_DIR_IN_HOST}/web-api/tmp-upload/:/app/tmp
      - ${PATH_LOCAL_DIR_IN_HOST}/fs/share-docs:/app/fs-docs
    command: python3 /app/bk_services/thumb_image.py
  thumb-office:
    image: nttlong/lv-file:b19
    container_name: thumb-office
    volumes:
      - ${PATH_LOCAL_DIR_IN_HOST}/web-api/tmp-upload/:/app/tmp
      - ${PATH_LOCAL_DIR_IN_HOST}/fs/share-docs:/app/fs-docs
    command: python3 /app/bk_services/thumb_office.py
  thumb-pdf:
    image: nttlong/lv-file:b19
    container_name: thumb-pdf
    volumes:
      - ${PATH_LOCAL_DIR_IN_HOST}/web-api/tmp-upload/:/app/tmp
      - ${PATH_LOCAL_DIR_IN_HOST}/fs/share-docs:/app/fs-docs

    command: python3 /app/bk_services/thumb_pdf.py
  fs-crawler:
    image: nttlong/fscrawler
    container_name: fs-crawler
#    build:
#      context: ./..
#      dockerfile: ./composer/fs-dockerfile
    command: >
      bash -c '
      
      sed -i "s/{FS_CRAWLER_INDEX}/${FS_CRAWLER_INDEX}/g"  /app/py_fs_crawler/fs_config/_settings.yaml &&
      sed  -i "s/{ES_URL}/http\:\/\/${ES_URL}/g" /app/py_fs_crawler/fs_config/_settings.yaml &&
      /usr/share/fscrawler/bin/fscrawler /app/py_fs_crawler/fs_config'
    volumes:
      - ${PATH_LOCAL_DIR_IN_HOST}/web-api/tmp-upload/:/app/tmp
      - ${PATH_LOCAL_DIR_IN_HOST}/fs/share-docs:/app/fs-docs
      - ${PATH_LOCAL_DIR_IN_HOST}/fs/fs-logs:/usr/share/fscrawler/logs

  files-es-index-all-office-files:
    image: nttlong/lv-file:b19
    container_name: files-es-index-all-office-files
    volumes:
      - ${PATH_LOCAL_DIR_IN_HOST}/web-api/tmp-upload/:/app/tmp
      - ${PATH_LOCAL_DIR_IN_HOST}/fs/share-docs:/app/fs-docs
    command: python3 /app/bk_services/fs_es_index.py
#
  ocr-image:
    image: nttlong/lv-file:b19
    volumes:
      - ${PATH_LOCAL_DIR_IN_HOST}/web-api/tmp-upload/:/app/tmp
      - ${PATH_LOCAL_DIR_IN_HOST}/fs/share-docs:/app/fs-docs

    command: python3 /app/bk_services/ocr_image.py
    container_name: ocr-image
  ocr-pdf:
    image: nttlong/lv-file:b19
    volumes:
      - ${PATH_LOCAL_DIR_IN_HOST}/web-api/tmp-upload/:/app/tmp
      - ${PATH_LOCAL_DIR_IN_HOST}/fs/share-docs:/app/fs-docs

    command: python3 /app/bk_services/ocr_pdf.py
    container_name: ocr-pdf
  cleansing-chapel:
    image: nttlong/lv-file:b19
    volumes:
      - ${PATH_LOCAL_DIR_IN_HOST}/kb-logs/:/app/logs
      - ${PATH_LOCAL_DIR_IN_HOST}/web-api/tmp-upload/:/app/tmp
      - ${PATH_LOCAL_DIR_IN_HOST}/fs/share-docs:/app/fs-docs

    command: python3 /app/bk_services/cleansing_chapel.py
    container_name: cleansing-chapel
  cleansing-town:
    image: nttlong/lv-file:b19
    volumes:
      - ${PATH_LOCAL_DIR_IN_HOST}/kb-logs/:/app/logs
      - ${PATH_LOCAL_DIR_IN_HOST}/web-api/tmp-upload/:/app/tmp
      - ${PATH_LOCAL_DIR_IN_HOST}/fs/share-docs:/app/fs-docs

    command: python3 /app/bk_services/cleansing_town.py
    container_name: cleansing-town

