#Full file service including:
# 1- Web API and Web app for documentation of storage
# 2- VideoService Process Thumb
version: '3.7'

services:
  build-mage:
    image: test
    build:
      context: ./..
      dockerfile: ./composer/test
  web:
    image: test
    container_name: test

    command: python3 /app/hello.py

