#Full file service including:
# 1- Web API and Web app for documentation of storage
# 2- Video Process Thumb
version: '3.7'

services:
  build-mage:
    image: lv-file
    build:
      context: ./..
      dockerfile: ./composer/files-dockerfile

  thumb-video:
    image: lv-file
    container_name: thumb-video
    volumes:
      - ${PATH_LOCAL_DIR_IN_HOST}/kb-logs/:/app/logs
      - ${PATH_LOCAL_DIR_IN_HOST}/web-api/tmp-upload/:/app/tmp
      - ${PATH_LOCAL_DIR_IN_HOST}/web-api/logs/:/app/logs
      - ${PATH_LOCAL_DIR_IN_HOST}/fs/share-docs:/app/fs-docs
    command: python3 /app/bk_services/thumb_video.py tmp-upload-folder=/app/tmp msg-folder=${MSG_FOLDER} fs-path=${FS_PATH} share-key=${SHARE_KEY} db-config=${DB_CONFIG}
