version: '3.7'

services:
  build-mage:
    image: lv-file
    build:
      context: ./..
      dockerfile: ./composer/files-dockerfile
  web:
    image: lv-file
    container_name: lv-file-web
    hostname: web
    volumes:

      - ${PATH_LOCAL_DIR_IN_HOST}/web-api/logs/:/app/logs
      - ${PATH_LOCAL_DIR_IN_HOST}/web-api/tmp-upload/:/app/tmp
#    command: python3 /app/api_app_dev_run.py --port 8000 --api-url http://${HOST_IP}:${API_PORT}
    command: gunicorn -w 4 --worker-class uvicorn.workers.UvicornWorker api_app:app --bind 0.0.0.0:80
    ports:
      - ${API_PORT}:80
    environment:
      - file_server_use_os_config='true'
      - file_server_db_host=192.168.18.36
      - file_server_db_port=27018
      - file_server_db_auth_source=lv-docs
      - file_server_db_replica_set=
      - file_server_db_username=admin-doc
      - file_server_db_password=123456
      - file_server_bind_port=80
      - file_server_bind_ip=0.0.0.0
      - file_server_root_url=http://${HOST_IP}:${API_PORT}
      - file_server_api_url=http://${HOST_IP}:${API_PORT}/api
      - file_server_es_url=http://${ES_URL},